name = "myOmniscape"
uuid = "1cfd598f-d836-46e8-8eba-64f08e408e0f"
authors = ["Sumuses"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
